### ISSUE TITLE
test: React Tracking Test

### ISSUE THREAD

**Issue by dev-heeseok** [kimkmin357/dev-web#4]
@kimkmin357 
Issue Tracking Test

1. Collaborator Issue 등록
2. Issue branch 생성
3. dev branch 최신 동기화 유지

**Comment by kimkmin357** [comment]
@dev-heeseok 
Collaborator가 브랜치도 생성할 수 있나보네요
Issue Tracking Test 브랜치를 main 브랜치와 동기화를 유지하려면 
Issue Tracking Test 브랜치 수정내용을 main에 merge해야하는 건가요?

**Comment by dev-heeseok** [comment]
@kimkmin357 
Issue-Tracking branch 를 dev branch 내용을 주기적으로 merge 할 예정입니다. 
(Test 용 branch 이므로 특별한 작업을 진행하는 것은 아닙니다.)

추가적으로 해당 branch 에서 Test 수정 후 Pull Request 를 요청하려고 합니다.
수정 사항에 대한 내용에 대해 코드 리뷰 부탁 드립니다.

**Comment by dev-heeseok** [comment]
@kimkmin357 
참고로 테스트를 수행하기 위한 Quick Start 를 작성해주면 코드를 살펴보는데 도움이 될 것 같습니다.

**Comment by dev-heeseok** [comment]
@kimkmin357
web-react repository 에서 Issue 마다 branch 를 생성하여 관리하고 있습니다. 참고용 History Graph 를 남깁니다.
![image](https://user-images.githubusercontent.com/97526196/167242843-f925bc1e-ca8f-41e7-88ab-e1574a509be4.png)

**Comment by dev-heeseok** [comment]
@kimkmin357 
issue-tracking branch 는 react-dev 를 tracking 하도록 하겠습니다.
