### ISSUE TITLE
Rename repository and modify folder structure

### ISSUE THREAD

**Issue by kimkmin357** [kimkmin357/dev-web#5]
@dev-heeseok @DeukHan
기존 Repository 이름을 변경하였습니다.
dev-react => dev-web

내부 폴더 구조도 변경하였습니다.
/nodejs : Nodejs 관련 스터디 내용
/react  : React 관련 스터디 내용

**Comment by dev-heeseok** [comment]
@kimkmin357 
생활코딩 2022 개정판 tutorial 구현까지 완료했군요!
Node.js 폴더 보니깐 Toy Project 가 있던데 프로젝트 설명과 관련된 내용은 어디에 있을까요?

**Comment by kimkmin357** [comment]
@dev-heeseok 
Toy-Project의 간단한 설명을 README.md파일에 추가하였습니다~
(nodejs/toy_proj/README.md)
